name = "copibot-webhook"
main = "worker.js"
compatibility_date = "2024-09-01"
workers_dev = true

[triggers]
crons = ["*/15 * * * *"]

[vars]
TZ = "America/Mexico_City"
DEBUG_LOG = "0"
STRICT_FAMILY_MATCH = "true"
SESSION_TTL_DAYS = "90"
LLM_MODEL = "gpt-4o-mini"
OPENAI_NLU_MODEL = "gpt-4o"
OPENAI_FALLBACK_MODEL = "gpt-4o-mini"

