name = "copibot-stg"
main = "worker.js"
compatibility_date = "2024-08-01"

[vars]
TZ = "America/Mexico_City"
STRICT_FAMILY_MATCH = "true"
DEBUG_LOG = "0"

[triggers]
crons = ["*/15 * * * *"]

[env.production]
name = "copibot"
main = "worker.js"
