name = "copibot-webhook"
main = "worker.js"
compatibility_date = "2024-09-01"

# Si usas cron desde el UI, puedes dejar esto; si quieres que quede versionado, descomenta:
[triggers]
crons = ["*/15 * * * *"]
