name: Deploy Worker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---------- 1) Construimos secrets.json y quitamos vacíos ----------
      - name: Build secrets.json
        run: |
          jq -n \
            --arg VERIFY_TOKEN           "${{ secrets.VERIFY_TOKEN }}" \
            --arg WA_TOKEN               "${{ secrets.WA_TOKEN }}" \
            --arg PHONE_ID               "${{ secrets.PHONE_ID }}" \
            --arg SUPABASE_URL           "${{ secrets.SUPABASE_URL }}" \
            --arg SUPABASE_SERVICE_ROLE  "${{ secrets.SUPABASE_SERVICE_ROLE }}" \
            --arg OPENAI_API_KEY         "${{ secrets.OPENAI_API_KEY }}" \
            --arg LLM_MODEL              "${{ secrets.LLM_MODEL }}" \
            --arg OPENAI_NLU_MODEL       "${{ secrets.OPENAI_NLU_MODEL }}" \
            --arg OPENAI_FALLBACK_MODEL  "${{ secrets.OPENAI_FALLBACK_MODEL }}" \
            --arg GCAL_CLIENT_ID         "${{ secrets.GCAL_CLIENT_ID }}" \
            --arg GCAL_CLIENT_SECRET     "${{ secrets.GCAL_CLIENT_SECRET }}" \
            --arg GCAL_REFRESH_TOKEN     "${{ secrets.GCAL_REFRESH_TOKEN }}" \
            --arg SUPPORT_PHONE_E164     "${{ secrets.SUPPORT_PHONE_E164 }}" \
            --arg SUPPORT_WHATSAPP       "${{ secrets.SUPPORT_WHATSAPP }}" \
            --arg TZ                     "${{ secrets.TZ }}" \
            --arg STRICT_FAMILY_MATCH    "${{ secrets.STRICT_FAMILY_MATCH }}" \
            --arg CRON_SECRET            "${{ secrets.CRON_SECRET }}" \
            --arg DEBUG_LOG              "${{ secrets.DEBUG_LOG }}" \
            --arg SESSION_TTL_DAYS       "${{ secrets.SESSION_TTL_DAYS }}" \
            '{
              VERIFY_TOKEN:           $VERIFY_TOKEN,
              WA_TOKEN:               $WA_TOKEN,
              PHONE_ID:               $PHONE_ID,
              SUPABASE_URL:           $SUPABASE_URL,
              SUPABASE_SERVICE_ROLE:  $SUPABASE_SERVICE_ROLE,
              OPENAI_API_KEY:         $OPENAI_API_KEY,
              LLM_MODEL:              $LLM_MODEL,
              OPENAI_NLU_MODEL:       $OPENAI_NLU_MODEL,
              OPENAI_FALLBACK_MODEL:  $OPENAI_FALLBACK_MODEL,
              GCAL_CLIENT_ID:         $GCAL_CLIENT_ID,
              GCAL_CLIENT_SECRET:     $GCAL_CLIENT_SECRET,
              GCAL_REFRESH_TOKEN:     $GCAL_REFRESH_TOKEN,
              SUPPORT_PHONE_E164:     $SUPPORT_PHONE_E164,
              SUPPORT_WHATSAPP:       $SUPPORT_WHATSAPP,
              TZ:                     $TZ,
              STRICT_FAMILY_MATCH:    $STRICT_FAMILY_MATCH,
              CRON_SECRET:            $CRON_SECRET,
              DEBUG_LOG:              $DEBUG_LOG,
              SESSION_TTL_DAYS:       $SESSION_TTL_DAYS
            } | with_entries(select(.value != null and .value != ""))' \
            > /tmp/secrets.json

          echo "Claves que se cargarán:"
          jq -r 'keys|join(", ")' /tmp/secrets.json

      # ---------- 2) Intento bulk ----------
      - name: Upload Cloudflare secrets (bulk)
        id: bulk
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true
        with:
          apiToken:  ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: secret bulk /tmp/secrets.json --name copibot-webhook

      # ---------- 3) Fallback si el bulk falla: subir 1x1 ----------
      - name: Install Wrangler CLI (for fallback)
        if: steps.bulk.outcome != 'success'
        run: npm i -g wrangler@3

      - name: Upload secrets individually (fallback)
        if: steps.bulk.outcome != 'success'
        env:
          CF_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          set -e
          uploaded=0
          jq -r 'to_entries[] | @base64' /tmp/secrets.json | while read -r row; do
            k=$(echo "$row" | base64 -d | jq -r '.key')
            v=$(echo "$row" | base64 -d | jq -r '.value')
            wrangler secret put "$k" --name copibot-webhook --text "$v"
            uploaded=$((uploaded+1))
          done
          echo "Subidas $uploaded secrets."

      # ---------- 4) Deploy ----------
      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --name copibot-webhook
