name: Deploy Worker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Aseguramos Wrangler CLI v3 (el action también lo usa, pero lo
      # instalamos para ejecutar `wrangler secret ...` en modo shell)
      - name: Install Wrangler v3
        run: npm i -g wrangler@3

      # ---- SUBIDA DE SECRETS (IDEMPOTENTE) ----
      # Si un secret ya existe o hay un binding homónimo, lo borramos y volvemos a crearlo.
      # NOTA: si en el dashboard creaste una *variable* (no "secret") con el mismo
      # nombre, bórrala en Cloudflare -> Workers -> Settings -> Variables & Secrets
      # o cámbiale el nombre. Las variables y los secrets comparten el mismo "binding".
      - name: Upload secrets (stdin, version-safe)
        env:
          CI: "1"
          WRANGLER_TELEMETRY: "0"

          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

          VERIFY_TOKEN:            ${{ secrets.VERIFY_TOKEN }}
          WA_TOKEN:                ${{ secrets.WA_TOKEN }}
          PHONE_ID:                ${{ secrets.PHONE_ID }}
          SUPABASE_URL:            ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE:   ${{ secrets.SUPABASE_SERVICE_ROLE }}
          OPENAI_API_KEY:          ${{ secrets.OPENAI_API_KEY }}
          LLM_MODEL:               ${{ secrets.LLM_MODEL }}
          OPENAI_NLU_MODEL:        ${{ secrets.OPENAI_NLU_MODEL }}
          OPENAI_FALLBACK_MODEL:   ${{ secrets.OPENAI_FALLBACK_MODEL }}
          GCAL_CLIENT_ID:          ${{ secrets.GCAL_CLIENT_ID }}
          GCAL_CLIENT_SECRET:      ${{ secrets.GCAL_CLIENT_SECRET }}
          GCAL_REFRESH_TOKEN:      ${{ secrets.GCAL_REFRESH_TOKEN }}
          SUPPORT_PHONE_E164:      ${{ secrets.SUPPORT_PHONE_E164 }}
          SUPPORT_WHATSAPP:        ${{ secrets.SUPPORT_WHATSAPP }}
          TZ:                      ${{ secrets.TZ }}
          STRICT_FAMILY_MATCH:     ${{ secrets.STRICT_FAMILY_MATCH }}
          CRON_SECRET:             ${{ secrets.CRON_SECRET }}
        run: |
          set -e
          export CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN}"
          export CLOUDFLARE_ACCOUNT_ID="${CLOUDFLARE_ACCOUNT_ID}"

          NAME="copibot-webhook"

          put_secret () {
            key="$1"; val="$2"
            if [ -n "$val" ]; then
              # Borramos si existiera (ignora error si no existe)
              yes | wrangler secret delete "$key" --name "$NAME" >/dev/null 2>&1 || true
              # Creamos de nuevo desde stdin
              printf '%s' "$val" | wrangler secret put "$key" --name "$NAME"
              echo "✓ $key actualizado"
            else
              echo "⚠️  $key vacío: omitido"
            fi
          }

          put_secret VERIFY_TOKEN          "$VERIFY_TOKEN"
          put_secret WA_TOKEN              "$WA_TOKEN"
          put_secret PHONE_ID              "$PHONE_ID"
          put_secret SUPABASE_URL          "$SUPABASE_URL"
          put_secret SUPABASE_SERVICE_ROLE "$SUPABASE_SERVICE_ROLE"
          put_secret OPENAI_API_KEY        "$OPENAI_API_KEY"
          put_secret LLM_MODEL             "$LLM_MODEL"
          put_secret OPENAI_NLU_MODEL      "$OPENAI_NLU_MODEL"
          put_secret OPENAI_FALLBACK_MODEL "$OPENAI_FALLBACK_MODEL"
          put_secret GCAL_CLIENT_ID        "$GCAL_CLIENT_ID"
          put_secret GCAL_CLIENT_SECRET    "$GCAL_CLIENT_SECRET"
          put_secret GCAL_REFRESH_TOKEN    "$GCAL_REFRESH_TOKEN"
          put_secret SUPPORT_PHONE_E164    "$SUPPORT_PHONE_E164"
          put_secret SUPPORT_WHATSAPP      "$SUPPORT_WHATSAPP"
          put_secret TZ                    "$TZ"
          put_secret STRICT_FAMILY_MATCH   "$STRICT_FAMILY_MATCH"
          put_secret CRON_SECRET           "$CRON_SECRET"

      # ---- DEPLOY ----
      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          # `wrangler.toml` en el root define nombre y entrypoint
          command: deploy
